# Generated by Django 5.1 on 2024-11-01 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChuyenMuc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='BaiViet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tieu_de', models.CharField(max_length=250)),
                ('noi_dung', models.TextField(blank=True, null=True)),
                ('ngay_tao', models.DateField()),
                ('nguoi_tao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BaiVietChuyenMuc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thu_tu', models.IntegerField()),
                ('bai_viet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qlbaiviet.baiviet')),
                ('chuyen_muc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qlbaiviet.chuyenmuc')),
            ],
        ),
        migrations.AddField(
            model_name='baiviet',
            name='chuyen_muc',
            field=models.ManyToManyField(through='qlbaiviet.BaiVietChuyenMuc', to='qlbaiviet.chuyenmuc'),
        ),
    ]
